name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm ts
      - run: pnpm test
      - run: pnpm build:client
      - run: pnpm build:server
      - run: pnpm test:boot
